Maquetado de Searchbar
LaraAReeves/UNSAM-Frontend pull request #21
Opened 2024-12-14 00:53 UTC by MelOviedo

Hiii!
Les comparto cómo quedó el maquetado de la barra de búsqueda. Utilicé Phosphor Icons para asegurarnos de que todos usemos la misma biblioteca de íconos recomendada por Fran, además del color que se utilizó en el Navbar.

![imagen](https://github.com/user-attachments/assets/bd54cc74-c5ff-40da-90c0-dceeb7bb03dd) 
![imagen](https://github.com/user-attachments/assets/692fbd81-db18-492d-a855-e6e031862f86)

2024-12-14 14:13 UTC, franncoronel commented on src/components/ui/SearchBar.tsx
> +       <MagnifyingGlass size={32} color='white'/>
Hola Mel, mejor quedemos en usar texto negro cuando estamos usando el color principal. Yo voy a cambiarlo en el Nav también, pero viste que los botones de acción principal siguen ese estilo: fondo azul, letra negra.

2024-12-14 14:54 UTC, franncoronel commented on src/components/ui/SearchBar.tsx
> +        style={{width: '100%'}}
Es necesario indicar fullWidth y la regla de width 100%?
Si la regla de css es necesaria, me parece que tendrías que incluirla en el prop sx que definiste más abajo, para evitar esa duplicación.

2024-12-14 14:54 UTC, franncoronel commented on src/components/ui/SearchBar.tsx
> +      />
Habría que agregar labels de accesibilidad. En este caso, una que describa que el usuario está parado sobre un campo de texto.
`aria-label='Ingresar búsqueda'` o algo por el estilo, cuesta ser descriptivo en pocas palabras.

2024-12-14 14:54 UTC, franncoronel commented on src/components/ui/SearchBar.tsx
> +          aria-label="Search"
Ya que esta `aria-label` la va a leer en voz alta un lector de pantalla para un posible usuario no vidente, debería estar en español.

2024-12-15 01:19 UTC, MelOviedo commented on src/components/ui/SearchBar.tsx
> +        style={{width: '100%'}}
Si iba a dejar solo el fullWidth y colgue en borrar el width 100%
gracias por notarlo

2024-12-15 22:29 UTC, franncoronel approved these changes
Creo que así ya estaría para mergear.

2024-12-16 00:45 UTC, agusnarvaez requested changes

2024-12-16 00:45 UTC, agusnarvaez commented on src/components/ui/SearchBar.tsx
> +export default function SeachBar() {
Está muy bien, lo único, para que este componente sea reutilizble, la búsqueda debe en el padre.
En le padre vas a tener: 
``` typescript
const [query, setQuery] = useState('')
```
 Así que deberías ver que searchbar se encargue nada más de recibir el `setQuery`, que será el texto a buscar. Y lo modifique cuando se ejcuta la búsqueda.
Finalmente en el padre cuando se cambia el texto de "query", va a realizar la búsqueda.

2024-12-16 02:24 UTC, agusnarvaez approved these changes
Joya, está para mergear 👍🏻

2024-12-16 02:25 UTC, merged