Maquetado de ClassRoomCard
LaraAReeves/UNSAM-Frontend pull request #24
Opened 2024-12-15 06:07 UTC by MelOviedo

Buenas, les dejo unos modelos de card para las aulas 
![imagen](https://github.com/user-attachments/assets/82b6289d-46c8-4b0e-8cd3-bde2d5fb3a17)
![imagen](https://github.com/user-attachments/assets/68ca1499-cc80-48ee-ad63-3045a45b8b1e)
![imagen](https://github.com/user-attachments/assets/db53ff3c-012f-48ab-aaaa-c4843acb8eb7)
![imagen](https://github.com/user-attachments/assets/e88637cd-fe0b-4999-ba62-f67d0d292c1d)

2024-12-15 22:26 UTC, franncoronel reviewed
Hola Mel, el que más me gustó es el modelo 4. Quizás agregaría un cuarto item con su ícono correspondiente para la carrera en vez de como está ahora, pero más allá de eso me re gustó.

2024-12-16 00:33 UTC, agusnarvaez commented on src/components/common/ClassRoomCard.tsx
> +            {/* <LocationOnIcon sx={{ color: 'text.secondary', mr: 1 }} /> */}
Eliminate los comentarios, así después no hay que estar limpiando el código de comments

2024-12-16 00:34 UTC, agusnarvaez commented on src/components/common/ClassRoomCard.tsx
> +              {/* <AccessTimeIcon sx={{ color: 'text.secondary', mr: 1 }} /> */}
Si esto es código necesario, agregale al comentario un `TODO: Este icono será para x cosa`

2024-12-16 00:37 UTC, agusnarvaez requested changes
A mi el modelo que mas me gustó fue el 4.

Dejate el modelo escogido y agregale la parametrización de los valores y con eso estamos 👍🏻

2024-12-16 00:37 UTC, agusnarvaez commented on src/components/common/ClassRoomCard.tsx
> +
Yo ya le agregaría la parametrización de los datos por prop

2024-12-16 00:37 UTC, agusnarvaez commented on src/components/pages/main/map/Map.tsx
> +      <ClassRoomCard/>
Y acá ya le pasaría los datos a usar de la card

2024-12-16 00:37 UTC, agusnarvaez commented on src/components/common/ClassRoomCard.tsx
> +
Acordate que hay 2 variantes, así que según los datos que vengan, debería identificar a que variante corresponde

2024-12-16 14:47 UTC, agusnarvaez requested changes
Quedaría cambiar `teachers `a `teachers[]` y con eso estaría

2024-12-16 14:47 UTC, agusnarvaez commented on src/components/common/ClassRoomCard.tsx
> +  teacher : string    //Tengo mis dudas si dejarlo como una lista o un string
Esto debería ser una lista, porque puede tener más de un profesor

2024-12-16 15:06 UTC, MelOviedo commented on src/components/common/ClassRoomCard.tsx
> +  teacher : string    //Tengo mis dudas si dejarlo como una lista o un string
Listo , hecha la correción

2024-12-16 20:33 UTC, agusnarvaez approved these changes
Joya, ya está para mergear

2024-12-16 20:36 UTC, merged